name: Semgrep

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Get Source Code
        uses: actions/checkout@v3

      - name: Run Semgrep Xss Rules

        run: semgrep ci --config=auto --sarif --output=semgrep.sarif || true

      - name: Upload Sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()